<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0"
  xmlns="http://relaxng.org/ns/structure/1.0"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
	xmlns:x="http://www.w3.org/1999/xhtml" >

  <xsl:output method="xml" version="1.0" encoding="UTF-8"
      omit-xml-declaration="no" indent="yes"/>
      <xsl:param name="profile.name" />
      <xsl:template match="/">
        
        <grammar xmlns="http://relaxng.org/ns/structure/1.0"
                 xmlns:x="http://www.w3.org/1999/xhtml">
          <x:h1>Z3986 Book Vocab Module</x:h1>
          <x:p>Do not manually edit this file - it is autogenerated from RDF</x:p>

          <define name="z3986.{$profile.name}.vocab" combine="choice">
          <choice>
            <xsl:for-each select="//*[@typeof='rdf:Property']">
              <value><xsl:value-of select="@id"/></value>
            </xsl:for-each>
          </choice>
        </define>
      </grammar>
      
    </xsl:template>
</xsl:stylesheet>